// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
	"gorm.io/gorm"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Message *string `json:"message,omitempty"`
	Token   *string `json:"token,omitempty"`
}

// Course defines model for Course.
type Course struct {
	gorm.Model
	Description *string `json:"description,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// CourseListResponse defines model for CourseListResponse.
type CourseListResponse struct {
	Data *[]Course `json:"data,omitempty"`
}

// Enrollment defines model for Enrollment.
type Enrollment struct {
	gorm.Model
	CourseId     *int       `json:"course_id,omitempty"`
	EnrollmentAt *time.Time `json:"enrollment_at,omitempty" gorm:"type:date"`
	StudentId    *int       `json:"student_id,omitempty"`
}

// EnrollmentRequest defines model for EnrollmentRequest.
type EnrollmentRequest struct {
	CourseId int `json:"course_id"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Module defines model for Module.
type Module struct {
	gorm.Model
	Content  *string `json:"content,omitempty"`
	CourseId *int    `json:"course_id,omitempty"`
	Title    *string `json:"title,omitempty"`
}

// ModuleListResponse defines model for ModuleListResponse.
type ModuleListResponse struct {
	Data *[]Module `json:"data,omitempty"`
}

// Score defines model for Score.
type Score struct {
	gorm.Model
	ModuleId  *int `json:"module_id,omitempty"`
	Score     *int `json:"score,omitempty"`
	StudentId *int `json:"student_id,omitempty"`
}

// ScoreListResponse defines model for ScoreListResponse.
type ScoreListResponse struct {
	Data *[]Score `json:"data,omitempty"`
}

// Student defines model for Student.
type Student struct {
	gorm.Model
	Email    *openapi_types.Email `json:"email,omitempty" gorm:"unique;not null"`
	Name     *string              `json:"name,omitempty"`
	Password *string              `json:"password,omitempty"`
}

// PostModuleModulIdSubmitScoreJSONBody defines parameters for PostModuleModulIdSubmitScore.
type PostModuleModulIdSubmitScoreJSONBody struct {
	Skor *int `json:"skor,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = Student

// PostEnrollmentJSONRequestBody defines body for PostEnrollment for application/json ContentType.
type PostEnrollmentJSONRequestBody = EnrollmentRequest

// PostModuleModulIdSubmitScoreJSONRequestBody defines body for PostModuleModulIdSubmitScore for application/json ContentType.
type PostModuleModulIdSubmitScoreJSONRequestBody PostModuleModulIdSubmitScoreJSONBody
