openapi: '3.0.4'
info: 
  title: lms project
  description: for study
  version: '1.0.0'

servers: 
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/pbenkyouuorganizatio/lms/1.0.0
  - url: http://localhost:8000
    description: local server

paths: 
  /auth/register:
    post: 
      tags: 
        - authentication
      summary: siswa baru daftar
      requestBody: 
        required: true
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/Student'
      responses: 
        '201':
          description: siswa berhasil daftar
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/AuthResponse'

  /auth/login:
    post: 
      tags: 
        - authentication
      summary: siswa login
      requestBody: 
        required: true
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/LoginRequest'
      responses: 
        '200':
          description: berhasil login
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/AuthResponse'

  /course:
    get: 
      tags: 
        - courses
      summary: ambil semua kursus
      responses: 
        '200':
          description: berhasil mengambil data kursus
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/CourseListResponse'

  /course/{course_id}:
    get: 
      tags: 
        - courses
      summary: ambil data kursus dari id
      parameters: 
        - name: course_id
          in: path
          required: true
          description: id dari kursus yang ingin dilihat
          schema: 
            type: integer
      responses: 
        '200':
          description: berhasil mengambil kursus dari id
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Course'

  /module:
    get: 
      tags: 
        - module
      summary: ambil semua modul
      responses: 
        '200':
          description: berhasil mengambil data modul
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/ModuleListResponse'
              
  /module/{module_id}:
    get: 
      tags: 
        - module
      summary: ambil modul berdasarkan id
      parameters: 
        - name: module_id
          in: path
          required: true
          schema: 
            type: integer
      responses: 
        '200':
          description: berhasil mengambil modul dari id
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Module'

  /enrollment:
    post:
      tags: 
        - enrollment
      summary:  daftar ke kursus
      requestBody: 
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/EnrollmentRequest'
      responses: 
        '200':
          description: berhasil mendaftar ke kursus ingin
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Enrollment'

  /my-courses:
    get:
      tags: 
        - enrollment
      responses: 
        '200':
          description: daftar kursus ditemukan
          content: 
            application/json: 
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Course'
            
  /my-score:
    get:
      tags: 
        - score
      summary: melihat nilai sendiri
      responses: 
        '200':
          description: data ditemukan
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/ScoreListResponse'

  /module/{modul_id}/submit-score:
    post: 
      tags: 
        - score
      summary: simpan skor untuk modul tertentu
      parameters: 
        - name: modul_id
          in: path
          required: true
          schema: 
            type: integer
      requestBody: 
        content: 
          application/json: 
            schema: 
              type: object
              properties: 
                skor:
                  type: integer
                  example: 90
      responses: 
        '201':
          description: nilai berhasil ditambahkan
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Score'
 
components: 
  schemas: 
    Student:
      type: object
      properties: 
        student_id:
          type: integer
          example: 01
        name:
          type: string
          example: "frey"
        email:
          type: string
          format: email
          example: "fr@gmail.com"
        password:
          type: string
          format: password
          example: "P4ssw0rd123"

    AuthResponse:
      type: object
      properties: 
        message:
          type: string
        token:
          type: string

    LoginRequest:
      type: object
      required: 
        - email
        - password
      properties: 
        email: {type: string, format: email}
        password: {type: string, format: password}

    Course:
      type: object
      properties: 
        course_id:
          type: integer
          example: 1
        title:
          type: string
          example: "golang"
        description:
          type: string
          example: "belajar golang"
    
    CourseListResponse:
      type: object
      properties: 
        data:
          type: array
          items: 
            $ref: '#/components/schemas/Course'

    Module:
      type: object
      properties: 
        module_id:
          type: integer
          example: 10
        course_id:
          type: integer
          example: 1
        title:
          type:  string
          example: "backend golang"
        content:
          type: string
          example: "belajar backend dengan golang"
      
    ModuleListResponse:
      type: object
      properties: 
        data:
          type: array
          items: 
            $ref: '#/components/schemas/Module'

    Enrollment:
      type: object
      properties: 
        enrollment_id:
          type: integer
          example: 001
        student_id:
          type: integer
          example: 01
        course_id:
          type: integer
          example: 1
        enrollment_at:
          type: string
          format: date
          example: "2026-03-20"
      
    EnrollmentRequest:
      type: object
      required: 
        - course_id
      properties: 
        course_id:
          type: integer
          example: 1

    Score:
      type: object
      properties: 
        score_id:
          type: integer
          example: 101
        student_id:
          type: integer
          example: 01
        module_id:
          type: integer
          example: 10
        score:
          type: integer
          example: 85
        
    ScoreListResponse:
      type: object
      properties: 
        data:
          type: array
          items: 
            $ref: '#/components/schemas/Score'